# generate_scene.sh param/radial16_noBastra_XXXL_fulltraffic.param
# generate_scene.sh param/radial16_XXXL_Bastra_nomaps_fulltraffic_logit50.param

generate_scene.sh param/radial16_XXXL_Bastra_rand05x8_timeALL_fulltraffic_logit05.param
generate_scene.sh param/radial16_XXXL_Bastra_rand05x8_timeALL_fulltraffic_logit10.param
generate_scene.sh param/radial16_XXXL_Bastra_rand05x8_timeALL_fulltraffic_logit20.param
generate_scene.sh param/radial16_XXXL_Bastra_rand05x8_timeALL_fulltraffic_logit50.param
generate_scene.sh param/radial16_XXXL_Bastra_rand05x8_timeALL_fulltraffic_logit100.param

generate_scene.sh param/radial16_XXXL_Bastra_rand05x1_timeALL_fulltraffic_logit50.param
generate_scene.sh param/radial16_XXXL_Bastra_rand05x2_timeALL_fulltraffic_logit50.param
generate_scene.sh param/radial16_XXXL_Bastra_rand05x4_timeALL_fulltraffic_logit50.param

