!/bin/bash

generate_scene.sh canogrid_Bastra_logit100_adhocmaps_fulltraffic.param
generate_scene.sh canogrid_Bastra_logit100_adhocmaps_randomtraffic.param
generate_scene.sh canogrid_Bastra_logit100_nomaps_fulltraffic.param
generate_scene.sh canogrid_Bastra_logit100_nomaps_randomtraffic.param
generate_scene.sh canogrid_Bastra_logit10_adhocmaps_fulltraffic.param
generate_scene.sh canogrid_Bastra_logit10_adhocmaps_randomtraffic.param
generate_scene.sh canogrid_Bastra_logit10_nomaps_fulltraffic.param
generate_scene.sh canogrid_Bastra_logit10_nomaps_randomtraffic.param
generate_scene.sh canogrid_Bastra_logit20_adhocmaps_fulltraffic.param
generate_scene.sh canogrid_Bastra_logit20_adhocmaps_randomtraffic.param
generate_scene.sh canogrid_Bastra_logit20_nomaps_fulltraffic.param
generate_scene.sh canogrid_Bastra_logit20_nomaps_randomtraffic.param
generate_scene.sh canogrid_Bastra_logit50_adhocmaps_fulltraffic.param
generate_scene.sh canogrid_Bastra_logit50_adhocmaps_randomtraffic.param
generate_scene.sh canogrid_Bastra_logit50_nomaps_fulltraffic.param
generate_scene.sh canogrid_Bastra_logit50_nomaps_randomtraffic.param
generate_scene.sh canogrid_noBastra_adhocmaps_dirtraffic.param
generate_scene.sh canogrid_noBastra_adhocmaps_fulltraffic.param
generate_scene.sh canogrid_noBastra_adhocmaps_randomtraffic.param
generate_scene.sh canogrid_noBastra_nomaps_dirtraffic.param
generate_scene.sh canogrid_noBastra_nomaps_fulltraffic.param
generate_scene.sh canogrid_noBastra_nomaps_randomtraffic.param
