# generate_city.sh param/madrid_barrio_salamanca_L_nomaps_tele60_fulltrafic.param
# generate_city.sh param/madrid_las_tablas_L_nomaps_tele60_fulltrafic.param
# generate_city.sh param/madrid_retiro_L_nomaps_tele60_fulltrafic.param

generate_city.sh param/madrid_barrio_salamanca_L_Bastra_rand05x8_timeALL_tele60_fulltrafic_logit50.param
generate_city.sh param/madrid_las_tablas_L_Bastra_rand05x8_timeALL_tele60_fulltrafic_logit50.param
generate_city.sh param/madrid_retiro_L_Bastra_rand05x8_timeALL_tele60_fulltrafic_logit50.param

generate_city.sh param/madrid_barrio_salamanca_L_Bastra_rand05x8_timeALL_tele60_fulltrafic_logit20.param
generate_city.sh param/madrid_las_tablas_L_Bastra_rand05x8_timeALL_tele60_fulltrafic_logit20.param
generate_city.sh param/madrid_retiro_L_Bastra_rand05x8_timeALL_tele60_fulltrafic_logit20.param

generate_city.sh param/madrid_barrio_salamanca_L_Bastra_rand05x8_timeALL_tele60_fulltrafic_logit100.param
generate_city.sh param/madrid_las_tablas_L_Bastra_rand05x8_timeALL_tele60_fulltrafic_logit100.param
generate_city.sh param/madrid_retiro_L_Bastra_rand05x8_timeALL_tele60_fulltrafic_logit100.param

generate_city.sh param/madrid_barrio_salamanca_L_Bastra_uni5x8_timeALL_tele60_fulltrafic_logit50.param
generate_city.sh param/madrid_las_tablas_L_Bastra_uni5x8_timeALL_tele60_fulltrafic_logit50.param
generate_city.sh param/madrid_retiro_L_Bastra_uni5x8_timeALL_tele60_fulltrafic_logit50.param

